---
galaxy_info:
  author: Digitalis.IO
  namespace: digitalis
  role_name: cassandra
  description: Digitalis Role Cassandra Apache
  company: Digitalis.IO
  license: Apache Licese 2.0

  min_ansible_version: 2.9

  platforms:
    - name: RedHat
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - ar-apache-cassandra-tarball

dependencies: []
