---
plugin: aws_ec2
keyed_groups:
  - key: tags
    prefix: tag

regions:
  - {{ lookup('ansible.builtin.env', 'AWS_DEFAULT_REGION') }}
filters:
  tag:ClusterName:
    - helios

strict_permissions: False
hostnames:
  - private-ip-address