galaxy_info:
  author: Daniel Schneller
  description: Installs an Azual Zulu JDK on Ubuntu
  company: Rheinwerk
  license: license (GPLv3)
  min_ansible_version: 2.7
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  galaxy_tags:
    - java
    - jdk
    - azul
    - zulu
dependencies: []
