---
- name: delete local.db
  file:
    path: /var/lib/axonops/local.db
    state: absent

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart axon-agent
  systemd:
    name: axon-agent
    state: restarted
    daemon_reload: yes
