---
# https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
- name: Set up Zulu repository
  when: "ansible_distribution_major_version|int >= 20"
  block:
    - name: Remove legacy config
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/apt/sources.list.d/repos_azulsystems_com_ubuntu.list

    - name: Add Zulu apt repository key.
      ansible.builtin.get_url:
        url: "{{ _zulu_jdk.apt_repo.key_url }}"
        dest: /etc/apt/trusted.gpg.d/azul.asc
        mode: '0644'
        force: true

    - name: Add Repo
      ansible.builtin.apt_repository:
        repo: "{{ _zulu_jdk.apt_repo.repo_line }}"
        state: present

- name: Apt Repo for Zulu
  when: "ansible_distribution_major_version|int < 20"
  block:
    - name: Add Repository Key by ID
      apt_key:
        id: "{{ _zulu_jdk.apt_repo.key_id }}"
        keyserver: "{{ _zulu_jdk.apt_repo.key_server | default('keyserver.ubuntu.com')  }}"
        state: present

    - name: Add Repository URL
      apt_repository:
        repo: "{{ _zulu_jdk.apt_repo.repo_line }}"
        state: present

    - name: Install Zulu Repo
      apt:
        state: latest
        name: "zulu-repo"

- name: Install Zulu JDK
  apt:
    state: "{% if zulu_version is defined and zulu_version != '' %}present{% else %}latest{% endif %}"
    name: "{{ _zulu_jdk.package_names }}"
    update_cache: true

- name: Check if security/java.security exists
  stat:
    path: "{{ _zulu_jdk.install_dir }}/security/java.security"
  register: _java_security

- name: "Set security setting for DNS cache ttl"
  lineinfile:
    path: "{{ _zulu_jdk.install_dir }}/security/java.security"
    regexp: '^(.*)networkaddress.cache.ttl=(.*)$'
    line: "networkaddress.cache.ttl={{ _zulu_jdk.security.dns_cache_ttl }}"
  when: _java_security.stat.exists

- name: "Set security setting for DNS cache negative ttl"
  lineinfile:
    path: "{{ _zulu_jdk.install_dir }}/security/java.security"
    regexp: '^(.*)networkaddress.cache.negative.ttl=(.*)$'
    line: "networkaddress.cache.negative.ttl={{ _zulu_jdk.security.dns_cache_negative_ttl }}"
  when: _java_security.stat.exists
