---

digitalis_repo_user: "{{ vault_digitalis_repo_user }}"
digitalis_repo_password: "{{ vault_digitalis_repo_password }}"

tarball_download_site: https://{{ digitalis_repo_user }}:{{ digitalis_repo_password }}@repo.digitalis.io/repository/ansible/
#https://downloads.apache.org/cassandra/3.11.9/apache-cassandra-3.11.9-bin.tar.gz

# The user that will own the Cassandra binary files. Should normally be root.
cassandra_binary_owner: root
cassandra_binary_group: root

cassandra_version: 3.11.9

#make sure to override default paramters:
cassandra_dc: TEST_DC
cassandra_max_heap_size: 1G
cassandra_streaming_keep_alive_period_in_secs: 300
cassandra_rack: RAC1

cassandra_jvm_parallel_gc_threads: 4
cassandra_jvm_conc_gc_threads: 4

java_home: /usr/bin/java
cassandra_log_silence_status_logger: true
cassandra_dynamic_snitch_enabled: true


# server_encryption_options:
cassandra_ssl_internode_encryption: none
cassandra_ssl_internode_keystore_file: conf/.keystore
cassandra_ssl_internode_keystore_pass: cassandra
cassandra_ssl_internode_protocol: TLS
cassandra_ssl_truststore_file: conf/.truststore
cassandra_ssl_truststore_pass: cassandra
cassandra_ssl_internode_require_client_auth: false
cassandra_require_endpoint_verification: false

cassandra_ssl_client_encryption_enabled: false
cassandra_ssl_client_encryption_optional: false
cassandra_ssl_client_keystore_file: conf/.keystore
cassandra_ssl_client_keystore_pass: cassandra
cassandra_ssl_client_require_client_auth: false
cassandra_ssl_client_encryption_protocol: TLS


cassandra_auto_bootstrap: true
cassandra_home_dir: "/opt/cassandra"
cassandra_install_dir: "/opt/apache-cassandra-{{ cassandra_version }}"
cassandra_symlink_homedir: true
cassandra_jmx_port: 7199
cassandra_jna_tmp_dir: /tmp
cassandra_java_tmp_dir: /tmp
cassandra_max_queued_native_transport_requests: 1024
cassandra_jvm_g1_rset_updating_pause_time_percent: 5
cassandra_jvm_max_gc_pause_ms: 500
cassandra_jvm_initiating_heap_occupancy_percentage: 40
cassandra_gc_log_dir: /var/log/cassandra
cassandra_jvm_gc_log_file_number: 10
cassandra_jvm_gc_log_file_max_size_mb: 10

cassandra_log_dir: /var/log/cassandra
cassandra_cluster_name: default
cassandra_num_tokens: 128
cassandra_hinted_handoff_enabled: true
cassandra_max_hint_window_in_ms: 10800000
cassandra_hinted_handoff_throttle_in_kb: 1024
cassandra_max_hints_delivery_threads: 2
cassandra_hints_directory: /data/cassandra/hints
cassandra_hints_flush_period_in_ms: 10000
cassandra_max_hints_file_size_in_mb: 128
cassandra_batchlog_replay_throttle_in_kb: 1024
cassandra_authenticator: PasswordAuthenticator
cassandra_authorizer: CassandraAuthorizer
cassandra_role_manager: CassandraRoleManager
cassandra_network_authorizer: AllowAllNetworkAuthorizer
cassandra_roles_validity_in_ms: 120000
cassandra_roles_update_interval_in_ms: 10000
cassandra_permissions_validity_in_ms: 60000
cassandra_permissions_update_interval_in_ms: 10000
cassandra_credentials_validity_in_ms: 120000
cassandra_credentials_update_interval_in_ms: 10000
cassandra_partitioner: org.apache.cassandra.dht.Murmur3Partitioner
cassandra_data_directory: /data/cassandra/data
cassandra_commitlog_directory: /data/cassandra/commitlog
cassandra_disk_failure_policy: die
cassandra_commit_failure_policy: die
cassandra_key_cache_size_in_mb: 512
cassandra_key_cache_save_period: 14400
cassandra_row_cache_class_name: org.apache.cassandra.cache.OHCProvider
cassandra_row_cache_size_in_mb: 0
cassandra_row_cache_save_period: 0
cassandra_counter_cache_size_in_mb: 50
cassandra_counter_cache_save_period: 7200
cassandra_saved_caches_directory: /data/cassandra/saved_caches
cassandra_commitlog_sync: periodic
cassandra_commitlog_sync_period_in_ms: 1000
cassandra_commitlog_segment_size_in_mb: 16
cassandra_seeds: 127.0.0.1
cassandra_concurrent_reads: 32
cassandra_concurrent_writes: 32
cassandra_concurrent_counter_writes: 32
cassandra_concurrent_materialized_view_writes: 32
cassandra_file_cache_size_in_mb: 512
cassandra_buffer_pool_use_heap_if_exhausted: true
cassandra_disk_optimization_strategy: ssd
cassandra_memtable_heap_space_in_mb: 1024
cassandra_memtable_offheap_space_in_mb: 4096
cassandra_memtable_cleanup_threshold: 0.22
cassandra_memtable_allocation_type: heap_buffers
cassandra_commitlog_total_space_in_mb: 16384
cassandra_memtable_flush_writers: 8
cassandra_index_summary_resize_interval_in_minutes: 60
cassandra_trickle_fsync: false
cassandra_trickle_fsync_interval_in_kb: 1024
cassandra_storage_port: 7000
cassandra_ssl_storage_port: 7001
cassandra_listen_interface: enp1s0f1
cassandra_listen_on_broadcast_address: false
cassandra_internode_authenticator: org.apache.cassandra.auth.AllowAllInternodeAuthenticator
cassandra_start_native_transport: true
cassandra_native_transport_port: 9042
cassandra_native_transport_max_threads: 256
cassandra_native_transport_max_frame_size_in_mb: 256
cassandra_start_rpc: false
cassandra_rpc_interface: enp1s0f0
cassandra_rpc_port: 9160
cassandra_rpc_keepalive: true
cassandra_rpc_server_type: sync
cassandra_rpc_min_threads: 4
cassandra_rpc_max_threads: 128
cassandra_thrift_framed_transport_size_in_mb: 16
cassandra_incremental_backups: false
cassandra_snapshot_before_compaction: false
cassandra_auto_snapshot: "true"
cassandra_tombstone_warn_threshold: 1000
cassandra_tombstone_failure_threshold: 100000
cassandra_column_index_size_in_kb: 64
cassandra_batch_size_warn_threshold_in_kb: 64
cassandra_batch_size_fail_threshold_in_kb: 640
cassandra_unlogged_batch_across_partitions_warn_threshold: 10
cassandra_concurrent_compactors: 1
cassandra_compaction_throughput_mb_per_sec: 16
cassandra_sstable_preemptive_open_interval_in_mb: 50
cassandra_stream_throughput_outbound_megabits_per_sec: 200
cassandra_inter_dc_stream_throughput_outbound_megabits_per_sec: 200
cassandra_read_request_timeout_in_ms: 5000
cassandra_range_request_timeout_in_ms: 10000
cassandra_write_request_timeout_in_ms: 2000
cassandra_counter_write_request_timeout_in_ms: 5000
cassandra_cas_contention_timeout_in_ms: 1000
cassandra_truncate_request_timeout_in_ms: 60000
cassandra_request_timeout_in_ms: 10000
cassandra_cross_node_timeout: false
cassandra_streaming_socket_timeout_in_ms: 86400000
cassandra_phi_convict_threshold: 8
cassandra_endpoint_snitch: GossipingPropertyFileSnitch
cassandra_dynamic_snitch_update_interval_in_ms: 100
cassandra_dynamic_snitch_reset_interval_in_ms: 600000
cassandra_dynamic_snitch_badness_threshold: 0.1
cassandra_internode_compression: dc
cassandra_inter_dc_tcp_nodelay: false
cassandra_tracetype_query_ttl: 86400
cassandra_tracetype_repair_ttl: 604800
cassandra_gc_log_threshold_in_ms: 200
cassandra_gc_warn_threshold_in_ms: 1000
cassandra_enable_user_defined_functions: false
cassandra_enable_scripted_user_defined_functions: false
cassandra_windows_timer_interval: 1
cassandra_max_value_size_in_mb: 256
cassandra_log_rotation_max: 20
cassandra_log_rotation_min: 1
cassandra_log_outbound_tcp_connection: disabled
cassandra_log_debug_repairs: disabled
cassandra_compaction_large_partition_warning_threshold_mb: 100
cassandra_prepared_statements_cache_size_mb: 20
cassandra_thrift_prepared_statements_cache_size_mb: 1
cassandra_column_index_cache_size_in_kb: 2
cassandra_slow_query_log_timeout_in_ms: 500
cassandra_back_pressure_enabled: false
cassandra_enable_materialized_views: true
cassandra_otc_coalescing_strategy: DISABLED

cassandra_cdc_enabled: false


cassandra_system_log_level: INFO

cassandra_graphite_jar: false
cassandra_jolokia_jar: false

cassandra_metrics_timeunit: SECONDS
cassandra_metrics_period: 30
cassandra_metrics_prefix: cassandra-clustername-node1
cassandra_metrics_host: 127.0.0.1
cassandra_metrics_port: 2003

cassandra_allocate_tokens_for_local_replication_factor: 3

jolokia_version: 1.3.5
graphite_version: 3.1.2

cassandra_cqlsh_port: "{{ cassandra_native_transport_port }}"
# Stops Ansible from adding the user/pass to ~/.cassandra/cqlshrc
# for additional security
cassandra_cqlsh_hide_auth: false

# Anything additional to add to the end of cassandra-env.sh, one line per array entry
cassandra_env_extra: []

#uncomment to specify the allowed  cipher suites:
# cassandra_cipher_suites_client_encryption: [ECDHE-RSA-AES256-SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
# cassandra_cipher_suites_server_encryption: [ECDHE-RSA-AES256-SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]

cassandra_audit_logging_options:
  enabled: false
  logger:
    - class_name: BinAuditLogger
  # audit_logs_dir:
  # included_keyspaces:
  # excluded_keyspaces: system, system_schema, system_virtual_schema
  # included_categories:
  # excluded_categories:
  # included_users:
  # excluded_users:
  # roll_cycle: HOURLY
  # block: true
  # max_queue_weight: 268435456 # 256 MiB
  # max_log_size: 17179869184 # 16 GiB
  ## archive command is "/path/to/script.sh %path" where %path is replaced with the file being rolled:
  # archive_command:
  # max_archive_retries: 10

# default options for full query logging - these can be overridden from command line when executing
# nodetool enablefullquerylog
# cassandra_full_query_logging_options:

cassandra_transparent_data_encryption_options:
  enabled: false
  chunk_length_kb: 64
  cipher: AES/CBC/PKCS5Padding
  key_alias: testing:1
  # CBC IV length for AES needs to be 16 bytes (which is also the default size)
  # iv_length: 16
  key_provider:
    - class_name: org.apache.cassandra.security.JKSKeyProvider
      parameters:
        - keystore: conf/.keystore
          keystore_password: cassandra
          store_type: JCEKS
          key_password: cassandra

cassandra_disk_access_mode: auto
