---
- name: cassandra user
  user:
    name: cassandra
    home: "{{ cassandra_log_dir }}"

- name: Cassandra binaries
  when: cassandra_download_url is defined and cassandra_download_url != ""
  unarchive:
    src: "{{ cassandra_download_url }}"
    dest: "/opt/"
    remote_src: true
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    creates: "{{ cassandra_install_dir }}"

- name: Cassandra binaries
  when: cassandra_download_url is not defined or cassandra_download_url == ""
  unarchive:
    src: "{{ tarball_download_site }}/cassandra/{{ cassandra_version }}/apache-cassandra-{{ cassandra_version }}-bin.tar.gz"
    dest: "/opt/"
    remote_src: true
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    creates: "{{ cassandra_install_dir }}"


- name: cassandra bin script with modified logdir
  template:
    src: "{{ cassandra_version }}/bin_cassandra.j2"
    dest: "{{ cassandra_install_dir }}/bin/cassandra"
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    mode: 0755
  when: cassandra_version is match("^4\.0.*") or cassandra_version is match("^3\.*")

- name: cassandra bin script with modified logdir (>= 4.1.0)
  template:
    src: "templates/4.1.x/bin_cassandra.j2"
    dest: "{{ cassandra_install_dir }}/bin/cassandra"
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    mode: 0755
  when: cassandra_version is match("^4\.1.[1|2]")

- name: cassandra bin script with modified logdir (>= 4.1.3)
  template:
    src: "templates/{{ cassandra_version }}/bin_cassandra.j2"
    dest: "{{ cassandra_install_dir }}/bin/cassandra"
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    mode: 0755
  when: cassandra_version is match("^4\.1.[3|4|5|6|7|8|9|10|11|12|13|14]")

- name: ensure Cassandra install directory has the correct owner
  file:
    path: "{{ cassandra_install_dir }}"
    state: directory
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
    mode: 0755

- name: ensure Cassandra node configured (4.0.x)
  template: src="{{ cassandra_version }}/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - cassandra-env.sh
    - cassandra-rackdc.properties
    - cassandra.yaml
    - logback.xml
  when: cassandra_version is match("^4\.0.*") or cassandra_version is match("^3\.*")

- name: ensure Cassandra node configured (4.1.0 4.1.1 4.1.2)
  template: src="4.1.x/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - cassandra-env.sh
    - cassandra-rackdc.properties
    - cassandra.yaml
    - logback.xml
  when: cassandra_version is match("^4\.1.[1|2]")

- name: ensure Cassandra node configured (4.1.3+)
  template: src="{{ cassandra_version }}/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - cassandra-env.sh
    - cassandra-rackdc.properties
    - cassandra.yaml
    - logback.xml
  when: cassandra_version is match("^4\.1.[3|4|5|6|7|8|9|10|11|12|13|14]")

- name: JVM options 3.x
  template: src="{{ cassandra_version }}/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - jvm.options
  when: cassandra_version is match("^3\..*")

- name: JVM options 4.x
  template: src="{{ cassandra_version }}/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - jvm-server.options
    - jvm11-server.options
    - jvm-clients.options
    - jvm11-clients.options
  when: cassandra_version is match("^4\.0.*")

- name: Deploy metrics.yml for Graphite
  template: src="{{ cassandra_version }}/conf/{{ item }}.j2"  dest="{{ cassandra_install_dir}}/conf/{{ item }}"
  with_items:
    - metrics.yaml
  when: cassandra_graphite_jar


- name: jolokia jar
  get_url:
    url: "{{ artifacts_repo_url }}/jolokia/jolokia-jvm-{{ jolokia_version }}-agent.jar"
    dest: "{{ cassandra_install_dir }}/lib/jolokia-jvm-{{ jolokia_version }}-agent.jar"
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
  when: cassandra_jolokia_jar

- name: metrics-graphite jar
  get_url:
    url: "{{ artifacts_repo_url }}/graphite/metrics-graphite-{{ graphite_version }}.jar"
    dest: "{{ cassandra_install_dir }}/lib/metrics-graphite-{{ graphite_version }}.jar"
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
  when: cassandra_graphite_jar


- name: Make sure uneeded .bat files from bin/ directory are removed
  shell: find {{ cassandra_install_dir }} -type f -name "*.bat" | grep '/bin/.*\.bat$' | xargs --no-run-if-empty rm

- name: Register existing cassandra home symlink
  stat:
    path: "{{ cassandra_home_dir }}"
  register: homelink

- name: Remove symlink for cassandra home
  file:
    state: absent
    dest: "{{ cassandra_home_dir }}"
  when: homelink.stat.exists and ((not homelink.stat.islnk) or homelink.stat.lnk_source != cassandra_install_dir)

- name: symlink cassandra home dir to install dir
  file:
    src: "{{ cassandra_install_dir }}"
    dest: "{{ cassandra_home_dir }}"
    state: link
    owner: "{{ cassandra_binary_owner }}"
    group: "{{ cassandra_binary_group }}"
  when: cassandra_symlink_homedir

- name: ensure Cassandra data directories and files are owned by Cassandra user
  file: path="{{ item }}"  state=directory  owner=cassandra  group=cassandra  recurse=yes mode=0750
  with_items:
    - "{{ cassandra_hints_directory }}"
    - "{{ cassandra_data_directory }}"
    - "{{ cassandra_commitlog_directory }}"
    - "{{ cassandra_saved_caches_directory }}"

- name: Log directories
  file: path="{{ item }}"  state=directory  owner=cassandra  group=cassandra  recurse=yes mode=0775
  with_items:
    - "{{ cassandra_log_dir }}"
    - "{{ cassandra_gc_log_dir }}"

- name: Cassandra default env variables
  template:
    src: default_cassandra.j2
    dest: /etc/default/cassandra
    mode: 0644


# - name: nodetool bash completion
#   copy:
#     src: bash_completion.d_nodetool
#     dest: /etc/bash_completion.d/nodetool
#     owner: root
#     group: root
#     mode: 0644


- name: add Cassandra binaries into the PATH
  lineinfile: dest=/etc/profile state=present line="PATH={{ cassandra_home_dir }}/bin:{{ cassandra_home_dir }}/tools/bin:$PATH"
