---
- name: Ensure pre-req gnupg is installed
  package:
    name: ['gnupg', 'apt-transport-https', 'debian-archive-keyring']
    state: present


- name: Add AxonOps apt repository key.
  apt_key:
    url: https://packages.axonops.com/apt/repo-signing-key.gpg
    validate_certs: yes


- name: Set AxonOps apt repository to {{ axon_agent_public_repository }}.
  apt_repository:
    repo: "deb https://packages.axonops.com/apt axonops-apt main"
    state: "{{ axon_agent_public_repository }}"
    update_cache: yes

- name: Set AxonOps beta apt repository to {{ axon_agent_beta_repository }}.
  apt_repository:
    repo: "deb https://packages.axonops.com/apt axonops-apt-beta main"
    state: "{{ axon_agent_beta_repository }}"
    update_cache: yes

# It is required for when you're updating versions
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
