---
- name: Start Cassandra
  hosts: "{% if target_name is defined %}tag_Name_{{target_name |replace('-', '_')}}{% elif target_ip is defined %}{{target_ip}}{% else %}all{% endif %}"
  gather_facts: true
  become: true
  any_errors_fatal: true
  tasks:
    - name: Start cassandra
      service:
        name: cassandra
        state: started

    - name: Wait for cassandra
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.interface }}"
        port: 9042
        delay: 30
        
