---
- name: Start Cassandra
  hosts: "tag_ClusterName_{{ lookup('env', 'TF_VAR_CASSANDRA_CLUSTER_NAME') }}:&tag_ClusterName_{{ lookup('env', 'TF_VAR_ENVIRONMENT') }}"
  gather_facts: true
  become: true
  any_errors_fatal: true
  order: sorted
  serial: 1
  tasks:
    - name: Start cassandra
      service:
        name: cassandra
        state: started

    - name: Wait for cassandra
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
        port: 9042
        delay: 30
        
