---
- name: Deploy Cassandra
  hosts: "tag_ClusterName_{{ cluster_name }},&tag_Role_cassandra"
  gather_facts: true
  become: true
  any_errors_fatal: true

  tasks:
    - debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"


