galaxy_info:
  author: Digitalis.IO DevOps
  description: Digitalis Role for ar-postgres
  company: Digitalis.IO
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  platforms:
  - name: CentOS
    versions:
    - 7
  - name: RedHat
    versions:
    - 7
  galaxy_tags:
  - lvmdisk

dependencies: []
