---

- name: Include Debian repos
  include_tasks: repo/Debian.yml
  when: ansible_os_family == "Debian"

- name: Include Redhat repos
  include_tasks: repo/RedHat.yml
  when: ansible_os_family == "RedHat"

# Online installation fixed version
- name: Ensure Axon agent is installed.
  package:
    name: "axon-agent={{ axon_agent_version }}"
    state: "{{ axon_agent_state }}"
  when: has_internet_access and axon_agent_version != ""
  notify: restart axon-agent

- name: Ensure AxonOps Java Agent {{ axon_java_agent }}={{ axon_java_agent_version }} is installed
  package:
    name: "{{ axon_java_agent }}={{ axon_java_agent_version }}"
    state: "{{ axon_agent_state }}"
  when: has_internet_access and axon_java_agent != '' and not axon_java_agent_force_offline_install and axon_java_agent_version != ""

# Online installation latest version
- name: Ensure Axon agent is installed.
  package:
    name: "axon-agent"
    state: "{{ axon_agent_state }}"
  when: has_internet_access and axon_agent_version == ""
  notify: restart axon-agent

- name: Ensure AxonOps Java Agent {{ axon_java_agent }} is installed
  package:
    name: "{{ axon_java_agent }}"
    state: "{{ axon_agent_state }}"
  when: has_internet_access and axon_java_agent != '' and not axon_java_agent_force_offline_install and axon_java_agent_version == ""

- name: Detect package type (deb)
  set_fact:
    pkg_ext: "deb"
  when: ansible_os_family == "Debian"

- name: Detect package type (rpm)
  set_fact:
    pkg_ext: "x86_64.rpm"
  when: ansible_os_family == "RedHat"

# Offline installation
- name: Copy AxonOps Agent package to target
  copy:
    src: "{{ axon_agent_download_path }}"
    dest: "/tmp/axon-agent-{{ axon_agent_version }}.{{ pkg_ext }}"
  when: not has_internet_access

- name: Install AxonOps Agent offline (rpm)
  package:
    name: "/tmp/axon-agent-{{ axon_agent_version }}.{{ pkg_ext }}"
    state: present
  when: ansible_os_family == "RedHat" and not has_internet_access

- name: Install AxonOps Agent offline (deb)
  apt:
    name: "/tmp/axon-agent-{{ axon_agent_version }}.{{ pkg_ext }}"
    deb: present
  when: ansible_os_family == "Debian" and not has_internet_access

- name: Copy AxonOps Java Agent package to target
  copy:
    src: "{{ axon_java_agent_download_path }}"
    dest: "/tmp/{{ axon_java_agent }}-{{ axon_java_agent_version }}.{{ pkg_ext }}"
  when: axon_java_agent != '' and (axon_java_agent_force_offline_install or not has_internet_access)

- name: Install AxonOps Java Agent offline (rpm)
  package:
    name: "/tmp/{{ axon_java_agent }}-{{ axon_java_agent_version }}.{{ pkg_ext }}"
    state: present
  when: ansible_os_family == "RedHat" and axon_java_agent != '' and (axon_java_agent_force_offline_install or not has_internet_access)

- name: Install AxonOps Java Agent offline (deb)
  apt:
    deb: "/tmp/{{ axon_java_agent }}-{{ axon_java_agent_version }}.{{ pkg_ext }}"
    state: present
  when: ansible_os_family == "Debian" and axon_java_agent != '' and (axon_java_agent_force_offline_install or not has_internet_access)

# TODO: Use an override in /etc/systemd instead of editing this file
- name: Configure axon-agent debug mode
  lineinfile:
    path: /lib/systemd/system/axon-agent.service
    regexp: "^ExecStart="
    insertafter: "^[Service]"
    line: "ExecStart=/usr/share/axonops/axon-agent{% if axon_agent_debug | default(false) %} -v 1{% endif %}"

- name: Make sure the agent is started on boot
  when: axon_agent_start_at_boot
  notify: reload systemd
  service:
    name: axon-agent
    state: started
    enabled: yes
