---
- set_fact:
    chrony_etc_root: /etc/chrony

- name: Install chrony
  package:
    name: "chrony"
    state: present

- name: Ensure /etc/chrony exists
  file:
    path: /etc/chrony
    state: directory

- name: Copy over config
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ chrony_etc_root }}/{{ item }}"
  with_items:
    - chrony.conf
  tags:
    - config
  notify:
    - restart chrony

- name: Ensure chrony daemon is started
  service:
    name: chrony
    enabled: yes
    state: started
  when: docker is not defined
